name: Java CI with Maven

on:
  push:
    branches:
      - devopsCI
    pull_request:
      types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build MS-application with Maven
        run: mvn -B clean package --file ./application/pom.xml -e

      - name: Build MS-conveyor with Maven
        run: mvn -B clean package --file ./conveyor/pom.xml -e

      - name: Build MS-deal with Maven
        run: mvn -B clean package --file ./deal/pom.xml -e

      - name: Build MS-dossier with Maven
        run: mvn -B clean package --file ./dossier/pom.xml -e

      - name: Build MS-gateway with Maven
        run: mvn -B clean package --file ./gateway/pom.xml -e

      - name: Test Coverage Application
        uses: codecov/codecov-action@v3
        with:
          directory: ./application
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Application

      - name: Test Coverage Conveyor
        uses: codecov/codecov-action@v3
        with:
          directory: ./conveyor
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Conveyor

      - name: Test Coverage Deal
        uses: codecov/codecov-action@v3
        with:
          directory: ./deal
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Deal

      - name: Test Coverage Dossier
        uses: codecov/codecov-action@v3
        with:
          directory: ./dossier
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Dossier

      - name: Test Coverage Gateway
        uses: codecov/codecov-action@v3
        with:
          directory: ./gateway
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Gateway


